config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      patch :finish
      patch :undone
    end
  end

  resources :lists

  resource :landing, only: [] do
    get :hello
    get :kitty
    get :directive
  end

  resource :data_driven, only: [] do
    get :example
  end

  get "/ng_templates/:path" => "ng_templates#page", constraints: { path: /.+/ }

  root to: "landings#hello"
end

app/models/list.rb
class List < ActiveRecord::Base

  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/data_drivens_controller.rb
class DataDrivensController < ApplicationController
  def example
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def hello
  end

  def kitty
  end

  def directive
    @lists = List.all
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/ng_templates_controller.rb
class NgTemplatesController < ApplicationController
  before_action :set_path

  def page
    begin
      render template: "ng_templates/#{@path}", layout: false
    rescue
      render_not_found and return false
    end
  end

  private

  def set_path
    @path = params[:path]
    render_not_found and return false if @path.blank?
    @path.sub!(/\/+$/, '')
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :finish, :undone]

  # GET /tasks
  # GET /tasks.json
  def index
    # @tasks = Task.all
    @tasks = Task.where(list_id: params[:list]).all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    list = List.find(params[:list_id])
    @task.list = list

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def finish
    @task.update(done: true)
    render action: 'show', formats: :json
  end

  def undone
    @task.update(done: false)
    render action: 'show', formats: :json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :done, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_drivens_helper.rb
module DataDrivensHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/data_drivens/example.html.erb
<%= javascript_include_tag 'data_driven' %>

Example na

<button type="button" class="hello-btn" data-type="human" data-name="Patthana">
  Human
</button>

<button type="button" class="hello-btn" data-type="human" data-name="James">
  Human
</button>

<button type="button" class="hello-btn" data-type="human" data-name="Jira S.">
  Human
</button>

<button type="button" class="hello-btn" data-type="dog" data-name="Doggy">
  Dog
</button>

<button type="button" class="hello-btn" data-type="first">
  First
</button>

<button type="button" class="hello-btn" data-type="pizza" data-topping="Hawaiian">
  Hawaiian Pizza
</button>

app/views/landings/directive.html.erb
<div class="row">
  <% @lists.each do |list| %>
    <todolist list-id="<%= list.id %>">
    </todolist>
  <% end %>
</div>

app/views/landings/kitty.html.erb
<div ng-controller="KittyController">
  <button type="button" ng-click="addList()">
    Add List
  </button>

  <hr/>

  <div ng-repeat="list in lists">
    List name: <input type="text" ng-model="list.name"><br/>

    <div ng-show="!list.newRecord">
      Task: <input type="text" ng-model="list.newTask">
      <button type="button" ng-click="addTask(list)">
        Add Task
      </button>
    </div>
    Tasks:<br/>

    <p ng-repeat="task in list.tasks">
      <span ng-class="{ done: task.done }">{{ task.description }}</span>

      <button type="button" ng-click="finishTask(task)" ng-show="!task.done">
        Done
      </button>

      <button type="button" ng-click="undoneTask(task)" ng-show="task.done">
        Undone
      </button>
    </p>

    <br/>

    <button type="button" ng-click="save(list)">
      Save List
    </button>

    <button type="button" ng-click="delete(list)">
      Delete List
    </button>
    <hr />
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Todolist">
<head>
  <title>AngularLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.done %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Done:</strong>
  <%= @task.done %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>